FROM mdillon/postgis

ARG http_proxy

RUN export http_proxy=${http_proxy} && \
    export https_proxy=${http_proxy} && \
    export HTTP_PROXY=${http_proxy} && \
    export HTTPS_PROXY=${http_proxy}

COPY ./_install /itag-install

RUN apt-get update && apt-get install -y wget unzip p7zip
RUN mkdir -p /itag/data
RUN cd /itag/data && \
    wget "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip" && \
    unzip ne_10m_coastline.zip && \
    wget "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip" && \
    unzip ne_10m_admin_0_countries.zip && \
    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip && \
    unzip ne_10m_admin_1_states_provinces.zip && \
    wget http://download.geonames.org/export/dump/allCountries.zip && \
    wget http://download.geonames.org/export/dump/alternateNames.zip && \
    unzip allCountries.zip && \
    unzip alternateNames.zip && \
    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_glaciated_areas.zip && \
    unzip ne_10m_glaciated_areas.zip && \
    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_rivers_lake_centerlines.zip && \
    unzip ne_10m_rivers_lake_centerlines.zip && \
    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_geography_marine_polys.zip && \
    unzip ne_10m_geography_marine_polys.zip && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01.7z' && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01.7z' && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01.7z' && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01.7z' && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01.7z' && \
    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_RGM04UTM38S_D976_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_RGM04UTM38S_D976_2015-12-01.7z' && \
    p7zip -d GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01.7z && \
    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01.7z && \
    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01.7z && \
    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01.7z && \
    p7zip -d GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01.7z
