FROM php:5-apache

ARG http_proxy

RUN export http_proxy=${http_proxy} && \
    export https_proxy=${http_proxy} && \
    export HTTP_PROXY=${http_proxy} && \
    export HTTPS_PROXY=${http_proxy}

ENV ITAG_HOME=/itag
ENV ITAG_DATA=$ITAG_HOME/data
ENV ITAG_TARGET=/var/www/itag

RUN apt-get update && apt-get install -y wget gdal-bin libpq-dev && \
    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql  && \
    docker-php-ext-install pdo pdo_pgsql pgsql


RUN mkdir -p $ITAG_DATA

COPY ./ $ITAG_HOME

#RUN cd $ITAG_DATA && \
#    wget "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip" && \
#    unzip ne_10m_coastline.zip
#    wget "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip" && \
#    unzip ne_10m_admin_0_countries.zip && \
#    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip && \
#    unzip ne_10m_admin_1_states_provinces.zip && \
#    wget http://download.geonames.org/export/dump/allCountries.zip && \
#    wget http://download.geonames.org/export/dump/alternateNames.zip && \
#    unzip allCountries.zip && \
#    unzip alternateNames.zip && \
#    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_glaciated_areas.zip && \
#    unzip ne_10m_glaciated_areas.zip && \
#    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_rivers_lake_centerlines.zip && \
#    unzip ne_10m_rivers_lake_centerlines.zip && \
#    wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_geography_marine_polys.zip && \
#    unzip ne_10m_geography_marine_polys.zip && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01.7z' && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01.7z' && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01.7z' && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01.7z' && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01.7z' && \
#    wget 'https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-COMMUNE_2015_2$GEOFLA_2-1_COMMUNE_SHP_RGM04UTM38S_D976_2015-12-01/file/GEOFLA_2-1_COMMUNE_SHP_RGM04UTM38S_D976_2015-12-01.7z' && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01.7z && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM20W84GUAD_D971_2015-12-01.7z && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM20W84MART_D972_2015-12-01.7z && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_UTM22RGFG95_D973_2015-12-01.7z && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_RGR92UTM40S_D974_2015-12-01.7z && \
#    p7zip -d GEOFLA_2-1_COMMUNE_SHP_RGM04UTM38S_D976_2015-12-01.7z

# General datasources
#RUN $ITAG_HOME/_install/installDatasources.sh -F -D $ITAG_DATA -H db

RUN $ITAG_HOME/_install/deploy.sh -s $ITAG_HOME -t $ITAG_TARGET
